# Generated by Django 6.0.2 on 2026-03-20 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CONSENT_CREATED", "Consent Created"),
                            ("PATIENT_APPROVED", "Patient Approved"),
                            ("PATIENT_REJECTED", "Patient Rejected"),
                            ("HOSPITAL_APPROVED", "Hospital Approved"),
                            ("HOSPITAL_REJECTED", "Hospital Rejected"),
                            ("CONSENT_DELETED", "Consent Deleted"),
                            ("RECORD_ACCESS_ATTEMPT", "Record Access Attempt"),
                            ("RECORD_ACCESS_SUCCESS", "Record Access Success"),
                            ("HASH_MATCHED", "Hash Matched"),
                            ("HASH_MISMATCH", "Hash Mismatch, Possible Tampering"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("performed_by", models.CharField(max_length=255)),
                ("consent_id", models.UUIDField(blank=True, null=True)),
                ("extra_info", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
