# Generated by Django 6.0.3 on 2026-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='scope_hospitals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CONSENT_CREATED', 'Consent Created'), ('PATIENT_APPROVED', 'Patient Approved'), ('PATIENT_REJECTED', 'Patient Rejected'), ('HOSPITAL_APPROVED', 'Hospital Approved'), ('HOSPITAL_REJECTED', 'Hospital Rejected'), ('CONSENT_DELETED', 'Consent Deleted'), ('RECORD_ACCESS_ATTEMPT', 'Record Access Attempt'), ('RECORD_ACCESS_DENIED', 'Record Access Denied'), ('RECORD_ACCESS_FAILED', 'Record Access Failed'), ('RECORD_ACCESS_SUCCESS', 'Record Access Success'), ('HASH_MATCHED', 'Hash Matched'), ('HASH_MISMATCH', 'Hash Mismatch, Possible Tampering'), ('CKD_PREDICTION_SUCCESS', 'CKD Prediction Success'), ('CKD_PREDICTION_FAILED', 'CKD Prediction Failed')], max_length=50),
        ),
    ]
