# Generated by Django 6.0.3 on 2026-03-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospital_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='license_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_locked',
            field=models.BooleanField(default=False),
        ),
    ]
