# Generated by Django 6.0.3 on 2026-03-10 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_license_locked_hospital_name_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email_verify_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
