# Generated by Django 6.0.3 on 2026-03-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_email_verified_hospital_email_verify_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='email_verify_token',
        ),
        migrations.AddField(
            model_name='hospital',
            name='email_verify_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email_verify_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
