# Generated by Django 6.0.3 on 2026-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaluser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Technician')], max_length=10),
        ),
    ]
