# Generated by Django 6.0.3 on 2026-03-25 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_alter_hospitaluser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaluser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Technician')], max_length=15),
        ),
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('nurse', 'Nurse'), ('technician', 'Technician')], max_length=15)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to='hospitals.hospitaluser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospitals.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='hospitals.hospitaluser')),
            ],
            options={
                'db_table': 'patient_assignments',
                'unique_together': {('patient', 'staff')},
            },
        ),
    ]
