# Generated by Django 6.0.3 on 2026-03-29 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_alter_hospitaluser_role_patientassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassignment',
            name='role',
            field=models.CharField(choices=[('nurse', 'Nurse')], max_length=15),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_type', models.CharField(choices=[('ckd', 'Chronic Kidney Disease')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'labs',
                'ordering': ['name'],
                'unique_together': {('hospital', 'lab_type')},
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chest_pain_type', models.CharField(choices=[('typical', 'Typical'), ('atypical', 'Atypical'), ('non_anginal', 'Non-anginal'), ('asymptomatic', 'Asymptomatic')], max_length=20)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hospitals.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='hospitals.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_lab_requests', to='hospitals.hospitaluser')),
            ],
            options={
                'db_table': 'lab_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordMeta',
            fields=[
                ('record_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('recorded_by_id', models.UUIDField()),
                ('sha256_hash', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_meta', to='hospitals.hospital')),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_meta', to='hospitals.labrequest')),
            ],
            options={
                'db_table': 'medical_record_meta',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LabAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hospitals.lab')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignments', to='hospitals.hospitaluser')),
            ],
            options={
                'db_table': 'lab_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('lab', 'technician')},
            },
        ),
    ]
