# Generated by Django 6.0.3 on 2026-03-29 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_alter_patientassignment_role_lab_labrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequestRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='hospitals.labrequest')),
                ('revised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_request_revisions', to='hospitals.hospitaluser')),
            ],
            options={
                'db_table': 'lab_request_revisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
