# Generated by Django 6.0.2 on 2026-04-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0012_labrequestrevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="lab_type",
            field=models.CharField(
                choices=[
                    ("pathology", "Pathology"),
                    ("radiology", "Radiology"),
                    ("cardiology", "Cardiology"),
                    ("microbiology", "Microbiology"),
                    ("biochemistry", "Biochemistry"),
                    ("hematology", "Hematology"),
                ],
                max_length=50,
            ),
        ),
    ]
