# Generated by Copilot to align lab type choices with the current model.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0013_alter_lab_lab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(
                choices=[
                    ('ckd', 'Chronic Kidney Disease'),
                    ('pathology', 'Pathology'),
                    ('radiology', 'Radiology'),
                    ('cardiology', 'Cardiology'),
                    ('microbiology', 'Microbiology'),
                    ('biochemistry', 'Biochemistry'),
                    ('hematology', 'Hematology'),
                ],
                max_length=50,
            ),
        ),
    ]