# Generated by Django 6.0.3 on 2026-04-19 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0015_lab_custom_fields_and_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('primary_diagnosis', models.CharField(max_length=255)),
                ('key_instruction', models.TextField()),
                ('doctor_note', models.TextField(blank=True, null=True)),
                ('handwritten_file', models.FileField(blank=True, null=True, upload_to='nurse_queue/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_queue_items_created', to='hospitals.hospitaluser')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_queue_items', to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_queue_items', to='hospitals.patient')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_queue_items_picked', to='hospitals.hospitaluser')),
            ],
            options={
                'db_table': 'nurse_queue_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
