# Generated by Django 6.0.3 on 2026-04-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0016_nursequeueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursequeueitem',
            name='follow_up_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='medications_administered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='nurse_observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='treatment_given',
            field=models.TextField(blank=True, null=True),
        ),
    ]
