# Generated by Django 6.0.3 on 2026-04-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0017_nursequeueitem_follow_up_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursequeueitem',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='nurse_tests_performed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='pulse_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='random_blood_sugar',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='spo2_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
