# Generated by Django 6.0.3 on 2026-04-23 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0018_nursequeueitem_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursequeueitem',
            name='closing_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='doctor_final_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='doctor_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='doctor_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='doctor_finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_finalized_queue_items', to='hospitals.hospitaluser'),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='doctor_medical_record_file',
            field=models.FileField(blank=True, null=True, upload_to='doctor_final_records/'),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='next_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='nurse_discharge_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
