# Generated by Django 6.0.3 on 2026-04-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0019_nursequeueitem_closing_statement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursequeueitem',
            name='finalized_record_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='finalized_record_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='finalized_record_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
