# Generated by Django 6.0.3 on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0020_nursequeueitem_finalized_record_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordmeta',
            name='record_type',
            field=models.CharField(choices=[('lab', 'Lab Record'), ('medical', 'Medical Record')], db_index=True, default='lab', max_length=16),
        ),
        migrations.AlterField(
            model_name='medicalrecordmeta',
            name='lab_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='record_meta', to='hospitals.labrequest'),
        ),
    ]