# Generated by Django 6.0.3 on 2026-05-03

from django.db import migrations


def forwards(apps, schema_editor):
    NurseQueueItem = apps.get_model('hospitals', 'NurseQueueItem')
    MedicalRecordMeta = apps.get_model('hospitals', 'MedicalRecordMeta')

    finalized_items = NurseQueueItem.objects.filter(
        doctor_finalized=True,
        finalized_record_id__isnull=False,
    ).select_related('hospital', 'patient', 'doctor_finalized_by', 'doctor')

    for item in finalized_items:
        MedicalRecordMeta.objects.update_or_create(
            record_id=item.finalized_record_id,
            defaults={
                'record_type': 'medical',
                'lab_request': None,
                'hospital_id': item.hospital_id,
                'patient_id': item.patient_id,
                'recorded_by_id': item.doctor_finalized_by_id or item.doctor_id,
                'sha256_hash': item.finalized_record_hash or '',
                'version': 1,
                'custom_field_values': item.finalized_record_payload or {},
            },
        )


def backwards(apps, schema_editor):
    MedicalRecordMeta = apps.get_model('hospitals', 'MedicalRecordMeta')
    MedicalRecordMeta.objects.filter(record_type='medical').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0021_medicalrecordmeta_record_type_and_nullable_lab_request'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]