# Generated by Django 6.0.3 on 2026-05-04

import uuid

from django.db import migrations, models


def backfill_medicalrecordmeta_ids(apps, schema_editor):
    MedicalRecordMeta = apps.get_model('hospitals', 'MedicalRecordMeta')
    for meta in MedicalRecordMeta.objects.all().iterator():
        meta.id = uuid.uuid4()
        meta.save(update_fields=['id'])


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0023_nursequeueitem_finalized_record_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordmeta',
            name='id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_medicalrecordmeta_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='medicalrecordmeta',
            name='record_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='medicalrecordmeta',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='medicalrecordmeta',
            unique_together={('record_id', 'version')},
        ),
    ]
