# Generated by Django 6.0.3 on 2026-05-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0024_medicalrecordmeta_versioned_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursequeueitem',
            name='change_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='change_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_queue_items_change_requested', to='hospitals.hospitaluser'),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='doctor_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='doctor_requested_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursequeueitem',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_queue_items_rejected', to='hospitals.hospitaluser'),
        ),
    ]
