# Generated by Django 6.0.3 on 2026-05-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0025_nursequeueitem_change_request_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursequeueitem',
            name='change_request_at',
        ),
        migrations.RemoveField(
            model_name='nursequeueitem',
            name='change_requested_by',
        ),
        migrations.RemoveField(
            model_name='nursequeueitem',
            name='doctor_requested_changes',
        ),
    ]
