# Generated by Django 6.0.3 on 2026-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0026_remove_nursequeueitem_change_request_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursequeueitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Patient weight in kg (optional)', max_digits=5, null=True),
        ),
    ]
