# Generated by Django 6.0.3 on 2026-05-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_patient_email_verification_fields'),
        ('hospitals', '0027_nursequeueitem_weight'),
    ]

    operations = [
    ]
