# Generated by Django 5.2.8 on 2026-02-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consentmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="consentrequest",
            constraint=models.UniqueConstraint(
                fields=(
                    "patient_id",
                    "requesting_hospital",
                    "requested_to_hospital",
                    "record_id",
                ),
                name="unique_consent_request",
            ),
        ),
    ]
