# Generated by Django 5.2.8 on 2026-02-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consentmanagement", "0002_consentrequest_unique_consent_request"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="consentrequest",
            name="unique_consent_request",
        ),
        migrations.AddConstraint(
            model_name="consentrequest",
            constraint=models.UniqueConstraint(
                fields=("patient_id", "requesting_hospital", "requested_to_hospital"),
                name="unique_patient_hospital_request",
            ),
        ),
    ]
