# Generated by Django 6.0.2 on 2026-02-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consentmanagement",
            "0003_remove_consentrequest_unique_consent_request_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("api_token", models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
    ]
