# Generated by Django 6.0.2 on 2026-03-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consentmanagement", "0004_hospitalidentity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HospitalIdentity",
        ),
    ]
