# Generated by Django 6.0.3 on 2026-03-29 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True)),
                ('lab_request_id', models.UUIDField(db_index=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('hospital_id', models.UUIDField(db_index=True)),
                ('recorded_by_id', models.UUIDField(db_index=True)),
                ('version', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('blood_glucose', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('ecg_result', models.CharField(choices=[('normal', 'Normal'), ('st_t_abnormality', 'ST-T abnormality'), ('lvh', 'LVH')], max_length=32)),
                ('sha256_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordVersion',
            fields=[
                ('version_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(db_index=True)),
                ('version_number', models.IntegerField()),
                ('data_snapshot', models.JSONField()),
                ('changed_by_id', models.UUIDField(db_index=True)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_record_versions',
                'ordering': ['-changed_at'],
            },
        ),
    ]
